

<?php include('include/header.php') ?>

<section>
  <div class="container">
    <div class="row">
      <div class="title">
        Business Purposes
      </div>
      <div class="business">
        <div class="business__block business__block--1">
          <div class="business__title">Website Notifications</div>
          <div class="business__text">Many CMSs support email notifications from scratch. If you want to receive messages from clients or any other notifications in directly in Telegram, you just need to put your Etlgr-email address in your CMS settings.</div>
        </div>
        <div class="business__block business__block--3">
          <div class="business__title">Trading alerts</div>
          <div class="business__text">Get a relatime notifications from your trading tools, such as <a href="#">https://www.tradingview.com/</a></div>
        </div>
        <div class="business__block business__block--5">
          <div class="business__title">CRM Notification</div>
          <div class="business__text">When you communicate with customers using CRM, speed of reaction may be very important. Don’t miss your customers due to slow analysis of email-notifications which is generated by CRM system.</div>
        </div>

        <div class="business__block business__block--2">
          <div class="business__title">IP cameras - motion detection</div>
          <div class="business__text">Etlgr bot can be used as a notification tool for receiving emails from IP cameras that detect motion. The most of CCTV cameras have an ability to send notifications using emails only. </div>
        </div>        
        <div class="business__block business__block--4">
          <div class="business__title">Open Circuit Notifications</div>
          <div class="business__text">Some of server-side hardware have a functionality of sending email notifications only. If you’re an IT company and you need to react immediately in case of damage or disconnection of your or your customers’ hardware, it’s better to have all your notifications directly in your favourite IM.</div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="title_dop">
        Personal Usage
      </div>
      <div class="business">
        <div class="business__block business__block--6">
          <div class="business__title">Smart House</div>
          <div class="business__text">Like IP-cameras, Smart House can send email messages. Receive information about gas leak, runed water, and opened windows and doors in your house as quick as possible.</div>
        </div>
        <div class="business__block business__block--9">
          <div class="business__title">Using Specific Services</div>
          <div class="business__text">Many services like calendars, organisers, reminders and so on can send email-notifications. Etlgr bot makes using it more easy and faster.</div>
        </div>
        <div class="business__block business__block--8">
          <div class="business__title">Communicate With Grandma And Grandpa</div>
          <div class="business__text">Many aged people using only email out of habit, not Social Networks or IM. With Etlgr Bot you can communicate with them the best way: they send you email and you receive it in IM-notification form. This may be useful when you travel on your holiday or you and your relatives live in different cities.</div>
        </div>
        <div class="business__block business__block--10">
          <div class="business__title">Hobby For Geeks</div>
          <div class="business__text">Many IT-specialists prefer keep hand on the pulse of new technologies. They experiment with it for maintaining a high professional level or as a hobby on a rest. Using Etlgm bot may be cheerful.</div>
        </div>
        <div class="business__block business__block--7">
          <div class="business__title">Notifications About Cataclysms</div>
          <div class="business__text">If you live in the area with risk of earthquake, tsunami, flood, storm, you need to immediately notification about cataclysms, but they may be transmitted only by email. Etlgr can help you receive this critical information right away.</div>
        </div>
      </div>
    </div>
  </div>
</section>      

<?php include('include/footer.php') ?>